---
# COPY this file to secrets.yml and modify as needed
development:
  DATABASE_URL: sqlite://db/local/development.db
  SECURE_DB_KEY: K4M1PorV7Drfevw1LcDhPQn/IIFdRoUG2A2U+Ui+/p4=
  SECURE_HASH_KEY: z2UbWZ05NbapyDM7m7oX4iTIOcb+f6/QwVRHedK9N8k=

test:
  DATABASE_URL: sqlite://db/local/test.db
  SECURE_DB_KEY: K4M1PorV7Drfevw1LcDhPQn/IIFdRoUG2A2U+Ui+/p4=
  SECURE_HASH_KEY: z2UbWZ05NbapyDM7m7oX4iTIOcb+f6/QwVRHedK9N8k=